function showSidebar(){const sidebar=document.querySelector('.sidebar');sidebar.classList.add('open')}
function hideSidebar(){const sidebar=document.querySelector('.sidebar');sidebar.classList.remove('open')}
document.addEventListener('DOMContentLoaded',function(){const sidebarLinks=document.querySelectorAll('.sidebar a');sidebarLinks.forEach(link=>{link.addEventListener('click',hideSidebar)});document.addEventListener('click',function(event){const sidebar=document.querySelector('.sidebar');const menuButton=document.querySelector('.menu-buttom');if(sidebar.classList.contains('open')&&!sidebar.contains(event.target)&&!event.target.closest('.menu-buttom')){hideSidebar()}})});document.addEventListener("DOMContentLoaded",function(){const numbers=document.querySelectorAll(".number");const observerOptions={root:null,rootMargin:"0px",threshold:0.5,};const observer=new IntersectionObserver(function(entries,observer){entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add("in-view");animateCount(entry.target.querySelector(".count"));observer.unobserve(entry.target)}})},observerOptions);numbers.forEach((number)=>{observer.observe(number)});function animateCount(element){const target=parseFloat(element.getAttribute("data-target"));const duration=3000;const fps=60;const totalFrames=(duration/1000)*fps;const increment=target/totalFrames;let current=0;function updateCount(){current+=increment;if(current>=target){current=target}else{requestAnimationFrame(updateCount)}
element.textContent=formatNumber(current,target)}
updateCount()}
function formatNumber(number,target){if(target===3){return Math.floor(number)}
if(target===2500){if(number<1000){return"+"+Math.floor(number)}else{return"+"+(number/1000).toFixed(1)+" mil"}}
return"+"+Math.floor(number)}});const imageBanner=document.querySelector('.image-banner');const images=Array.from(document.querySelectorAll('.image-banner img'));const totalImages=images.length;let currentIndex=0;let autoSlideInterval;const getSettings=()=>({isMobile:window.innerWidth<=768,gap:parseInt(getComputedStyle(imageBanner).gap)||0,clonesQty:window.innerWidth<=768?1:3});let settings=getSettings();let imageWidth=images[0].clientWidth+settings.gap;const setupClones=()=>{const existingClones=imageBanner.querySelectorAll('.clone');existingClones.forEach(clone=>clone.remove());const firstClones=images.slice(0,settings.clonesQty).map(img=>{const c=img.cloneNode();c.classList.add('clone');return c});const lastClones=images.slice(-settings.clonesQty).map(img=>{const c=img.cloneNode();c.classList.add('clone');return c});lastClones.reverse().forEach(clone=>imageBanner.insertBefore(clone,imageBanner.firstChild));firstClones.forEach(clone=>imageBanner.appendChild(clone))};setupClones();imageBanner.style.transform=`translateX(${-settings.clonesQty * imageWidth}px)`;function showNextImage(){currentIndex++;imageBanner.style.transition='transform 0.5s ease-in-out';imageBanner.style.transform=`translateX(${-(currentIndex + settings.clonesQty) * imageWidth}px)`;if(currentIndex>=totalImages){currentIndex=0;setTimeout(()=>{imageBanner.style.transition='none';imageBanner.style.transform=`translateX(${-settings.clonesQty * imageWidth}px)`},500)}
updateNavigation()}
function updateNavigation(){const sectionSize=settings.isMobile?1:Math.ceil(totalImages/document.querySelectorAll('.navigation input').length);const sectionIndex=Math.floor(currentIndex/sectionSize);document.querySelectorAll('.navigation input').forEach((input,i)=>{input.checked=i===sectionIndex})}
document.querySelectorAll('.navigation input').forEach((input,index)=>{input.addEventListener('change',()=>{const sectionSize=settings.isMobile?1:Math.ceil(totalImages/document.querySelectorAll('.navigation input').length);currentIndex=index*sectionSize;imageBanner.style.transition=`transform 0.5s ease-in-out`;imageBanner.style.transform=`translateX(${-(currentIndex + settings.clonesQty) * imageWidth}px)`;clearInterval(autoSlideInterval);setTimeout(()=>{autoSlideInterval=setInterval(showNextImage,4500)},8000)})});imageBanner.addEventListener('touchstart',e=>{touchStartX=e.touches[0].clientX;clearInterval(autoSlideInterval)},{passive:!0});imageBanner.addEventListener('touchend',e=>{const touchEndX=e.changedTouches[0].clientX;const diff=touchStartX-touchEndX;if(Math.abs(diff)>50){if(diff>0)showNextImage();else if(currentIndex>0)currentIndex-=2}
autoSlideInterval=setInterval(showNextImage,4500)},{passive:!0});window.addEventListener('resize',()=>{settings=getSettings();imageWidth=images[0].clientWidth+settings.gap;setupClones();imageBanner.style.transform=`translateX(${-settings.clonesQty * imageWidth}px)`;currentIndex=0;updateNavigation()},{passive:!0});const prevButton=document.getElementById('prevButton');const nextButton=document.getElementById('nextButton');function showPreviousImage(){currentIndex--;if(currentIndex<0){currentIndex=totalImages-1;imageBanner.style.transition='none';imageBanner.style.transform=`translateX(${-(totalImages + settings.clonesQty) * imageWidth}px)`;setTimeout(()=>{imageBanner.style.transition='transform 0.5s ease-in-out';currentIndex=totalImages-1;imageBanner.style.transform=`translateX(${-(currentIndex + settings.clonesQty) * imageWidth}px)`},10)}else{imageBanner.style.transition='transform 0.5s ease-in-out';imageBanner.style.transform=`translateX(${-(currentIndex + settings.clonesQty) * imageWidth}px)`}
updateNavigation()}
prevButton.addEventListener('click',()=>{clearInterval(autoSlideInterval);showPreviousImage();autoSlideInterval=setInterval(showNextImage,4500)});nextButton.addEventListener('click',()=>{clearInterval(autoSlideInterval);showNextImage();autoSlideInterval=setInterval(showNextImage,4500)});window.addEventListener('resize',()=>{settings=getSettings();imageWidth=images[0].clientWidth+settings.gap;setupClones();imageBanner.style.transform=`translateX(${-settings.clonesQty * imageWidth}px)`;currentIndex=0;updateNavigation();if(settings.isMobile){document.querySelector('.catalog').style.padding='0 20px'}else{document.querySelector('.catalog').style.padding='0'}});document.addEventListener("DOMContentLoaded",()=>{const overlay=document.querySelector('.loading-overlay');const carrossel=document.querySelector('.carrossel');const container=document.querySelector('.container-slider');if(!overlay||!carrossel||!container)return;const loadImage=(img)=>{return new Promise((resolve,reject)=>{if(img.dataset.src&&!img.src){img.src=img.dataset.src;img.onload=()=>resolve();img.onerror=()=>reject()}else{resolve()}})};const loadVisibleImages=async()=>{const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){loadImage(entry.target).then(()=>{loadedImages++;checkLoadingState()});observer.unobserve(entry.target)}})},{rootMargin:'200px',threshold:0.01});document.querySelectorAll('.item-slider img').forEach(img=>{observer.observe(img)})};const hideOverlay=()=>{overlay.classList.add('hidden');setTimeout(()=>{overlay.remove();container.classList.add('loaded')},500)};let loadedImages=0;let hasErrors=!1;const initialImages=Array.from(document.querySelectorAll('.item-slider:nth-child(-n+4) img'));Promise.all(initialImages.map(loadImage)).then(()=>{loadedImages+=initialImages.length;checkLoadingState()}).catch(()=>hasErrors=!0);loadVisibleImages();const checkLoadingState=()=>{if(loadedImages>=4)hideOverlay();if(loadedImages===0&&hasErrors){setTimeout(hideOverlay,2000)}};let timeout=setTimeout(()=>{if(loadedImages===0)hideOverlay();},19000);overlay.addEventListener('transitionend',()=>clearTimeout(timeout))});const menuLinks=document.querySelectorAll('.nav-list a[href^="#"], .sidebar a[href^="#"]');let isAnimating=!1;let lastClick=0;function smoothScrollTo(targetPosition,duration=1200){const startPosition=window.pageYOffset;const distance=targetPosition-startPosition;let startTime=null;isAnimating=!0;function animation(currentTime){if(!startTime)startTime=currentTime;const timeElapsed=currentTime-startTime;const progress=Math.min(timeElapsed/duration,1);const ease=progress<0.5?2*progress*progress:1-Math.pow(-2*progress+2,2)/2;window.scrollTo(0,startPosition+distance*ease);if(timeElapsed<duration){requestAnimationFrame(animation)}else{isAnimating=!1}}
requestAnimationFrame(animation)}
function handleScroll(event){event.preventDefault();if(isAnimating||Date.now()-lastClick<1000)return;lastClick=Date.now();const targetUrl=new URL(event.target.href);const currentUrl=new URL(window.location.href);if(targetUrl.pathname!==currentUrl.pathname){window.location.href=targetUrl.href;return}
const hash=targetUrl.hash;const target=document.querySelector(hash);if(target){const header=document.querySelector('header');const headerHeight=header?header.offsetHeight:90;const targetPosition=target.offsetTop-headerHeight;smoothScrollTo(targetPosition);history.pushState(null,null,hash)}}
function handleHashScroll(){const hash=window.location.hash;if(hash){const target=document.querySelector(hash);if(target){const header=document.querySelector('header');const headerHeight=header?header.offsetHeight:90;const targetPosition=target.offsetTop-headerHeight;smoothScrollTo(targetPosition,800)}}}
document.addEventListener('DOMContentLoaded',handleHashScroll);window.addEventListener('popstate',handleHashScroll);menuLinks.forEach(link=>link.addEventListener('click',handleScroll));const recordesObserver=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){const img=entry.target;if(!img.src&&img.dataset.src){img.src=img.dataset.src}
img.onload=()=>img.classList.add('loaded');recordesObserver.unobserve(img)}})},{rootMargin:'200px',threshold:0.1});document.querySelectorAll(`
  .main-image img,
  .small-images img,
  .mobile-recorde img,
  img.lazy-img
`).forEach(img=>{img.loading='lazy';recordesObserver.observe(img)});const bannerObserver=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){const img=entry.target;if(img.dataset.src){const promise=new Promise((resolve)=>{img.src=img.dataset.src;img.decode().then(resolve)});promise.then(()=>{img.classList.add('loaded');img.removeAttribute('data-src');bannerObserver.unobserve(img)})}}})},{rootMargin:'300px',threshold:0.01});document.querySelectorAll('.banner-floresta, .banner-marca').forEach(banner=>{bannerObserver.observe(banner)});const mapObserver=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){const container=entry.target;const iframe=container.querySelector('iframe');if(iframe&&!iframe.src&&iframe.dataset.src){iframe.src=iframe.dataset.src;iframe.onload=()=>{container.classList.add('loaded');iframe.classList.add('loaded')}}
mapObserver.unobserve(container)}})},{rootMargin:'300px',threshold:0.01});document.querySelectorAll('.map').forEach(container=>{mapObserver.observe(container)})